// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TexasWalks.API.Data;

#nullable disable

namespace TexasWalks.API.Migrations
{
    [DbContext(typeof(TexasWalksDbContext))]
    [Migration("20250902042932_Seeding data for difficulties and Regions")]
    partial class SeedingdatafordifficultiesandRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TexasWalks.API.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3dcf8f49-d451-4c87-a270-365c1da9d2c1"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("2741d36f-4932-4448-8f78-ab458f163fad"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("6ace00c4-4ac4-4b69-b832-965438d482c0"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("TexasWalks.API.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TexasWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f959f132-ff89-4ca5-a870-b6e5b4eec0c4"),
                            Code = "COP",
                            Name = "Coppel",
                            RegionImageUrl = "image.jpg"
                        },
                        new
                        {
                            Id = new Guid("f6874358-c635-4b21-a401-b5c3f6eafec2"),
                            Code = "NTL",
                            Name = "Northland",
                            RegionImageUrl = "image.jpg"
                        },
                        new
                        {
                            Id = new Guid("132f75be-ab4c-460a-821e-149e7899c5b9"),
                            Code = "BOP",
                            Name = "Bay Of Plenty",
                            RegionImageUrl = "image.jpg"
                        },
                        new
                        {
                            Id = new Guid("0b42603b-e20a-4365-9996-042057541580"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "image.jpg"
                        },
                        new
                        {
                            Id = new Guid("8a34d69b-e451-489b-b37a-830687ca47d8"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "image.jpg"
                        },
                        new
                        {
                            Id = new Guid("2ff57e7d-2a87-4038-92b3-6907fd9f3da6"),
                            Code = "STL",
                            Name = "Southland",
                            RegionImageUrl = "image.jpg"
                        });
                });

            modelBuilder.Entity("TexasWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Walks");
                });
#pragma warning restore 612, 618
        }
    }
}
